__project_name__ = "khayyam_api"
__author__ = "Pooria Soltani"
__email__ = "pooria.ms@gmail.com"
__linkedin__ = "https://www.linkedin.com/in/pmsoltani"
__description__ = "A dead simple Jalali API"
__version__ = "0.1.2"
__license__ = "MIT"
__repo__ = "https://github.com/pmsoltani/khayyam_api"
